name: Retrieve latest headlines

on: [workflow_dispatch]

# on:
#   schedule:
#    - cron: '30 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration

    steps:
        uses: actions/checkout@v3.3.0
      
      # Environment
      - name: Use Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10.4'
          cache: 'pip'

      # Dependencies
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4==4.11.2
          pip install requests==2.28.2

      - name: Run Script
        run: |
          python update.py

      - name: Run Script
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
