name: Retrieve latest headlines

on: [workflow_dispatch]

# on:
#   schedule:
#    - cron: '30 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0
      
      - name: Use Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10.4'

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        run: python update.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Updated headlines" -a

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
